name: pet_pal
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  get: ^4.6.6
  flutter_otp_text_field: ^1.1.1
  intl_phone_field: ^3.2.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  fluttertoast: ^8.2.5
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.1.0
  dropdown_button2: ^2.3.9
  email_otp: ^2.1.2
  flutter_slidable: ^3.1.0
  audioplayers: ^6.0.0
  flutter_launcher_icons: ^0.13.1

  firebase_storage: ^11.6.5
  firebase_auth: ^4.17.0
  firebase_core: ^2.25.0
  cloud_firestore: ^4.15.0
  url_launcher: ^6.2.6
  google_generative_ai: ^0.4.0
  flutter_markdown: ^0.7.1
  lottie: ^3.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/pet_pal_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/music/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
